### PR TITLE
Error Page

### PR DESCRIPTION
**Pull request by yeshasimaria**
@jkcheong92 Set RecordNotFound and ActionNotFound Exceptions to an error page, styled error page based on Burrple's one.

### CODE REVIEW

**Comment by jkcheong92** [comment]
@yeshasimaria Too many files edited - are all these just for the error page? Or are some of the files from android branch? @junwen29 please advice.

**Comment by yeshasimaria** [comment]
Hey! I edited only 2 files, and only saw 2 when I commited for the error page branch! My android related stuff is on a different branch. I don't know why there are so many over here :O Did I commit wrongly or sth?

**Comment by jkcheong92** [comment]
@yeshasimaria Hmm, i not sure. Maybe u committed other work while on that branch. Safest way to do now is to 
1. Checkout to develop and pull in latest develop
2. Checkout a new branch from this updated develop branch
3. Redo your work (i.e. your 2 files)
4. Make a pull request with the new branch

**Comment by junwen29** [comment]
@jkcheong92 those other commits are my commits for android api @yeshasimaria i think jk's instructions are good and it works that way too.

**Comment by yeshasimaria** [comment]
@junwen29 I see. Anyway I tried doing what @jkcheong92 suggested, hope its better now! :)

**Pull request closed without merging**
